### ISSUE TITLE
Unable to find destination data template

### ISSUE THREAD

**Issue by mcgrievm** [aldefouw/redcap-api-transfer#14]
Not sure if you're still actively maintaining this project, but I'm getting the below error when trying to transfer a project. Note that I previously posted a bug report as "senorrojo" a few years ago (which you solved - thank you) and I've just started using this package again because we're migrating from one REDCap server to another. Thank you so much for creating this project - it truly saved me the last time I needed it and I had many, many successful transfers of large projects.

I get the same error for transferring a single record or all records:

[matt@localhost redcap-api-transfer]# sh transfer_single_record.sh Test 25
/app/library/export_data.rb:50:in `throw': uncaught throw "Unable to find a destination data template file for the project /app/export_data/dest_template-1708116087.tmp." (UncaughtThrowError)
        from /app/library/export_data.rb:50:in `fetch_dest_data_template'
        from /app/library/export_data.rb:43:in `dest_data_cols'
        from /app/library/export_data.rb:15:in `initialize'
        from /app/library/transfer_records.rb:50:in `new'
        from /app/library/transfer_records.rb:50:in `initialize'
        from transfer_single_record.rb:7:in `new'
        from transfer_single_record.rb:7:in `\<main\>'
Loading Configuration ...
Downloading SOURCE Project Template ...
Downloading DESTINATION Project Template ...
Downloading Data Dictionary ...
Loading Export Data ...
[matt@localhost redcap-api-transfer]#

[matt@localhost redcap-api-transfer]# ls app/export_data/
data.csv

data.csv has a CSV export of the project data from the SOURCE. I also tried putting the data dictionary in that export_data directory to no avail. Below is my config file. I'm happy to provide verbose logging or any other information that might be helpful. 

```
settings:
  processes: 8 # Default number of processes the script will fallback to if none is specified in specific projects below
  verbose: false # When true, outputs additional information to logs about the HTTP requests being made

projects:
  Test:
    source:
      url: https://redcap.healthsciencessc.org/api/
      token: XXXX

    destination:
      url: https://redcap.research.sc.edu/api/
      token: YYYY

    transfer_new_records_only: true # Must have API Export Rights on Destination REDCap Server!
    processes: 8 # Takes precedence over the processes listed in settings
    verbose: false  # Takes precedence over the verbose flag listed in settings
```

Again, thank you!
